//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkwoodEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarkwoodEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainFormBg {
            get {
                object obj = ResourceManager.GetObject("mainFormBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Version Compatibility: .
        /// </summary>
        internal static string majrVerCom {
            get {
                return ResourceManager.GetString("majrVerCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Version: .
        /// </summary>
        internal static string majVer {
            get {
                return ResourceManager.GetString("majVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Version: .
        /// </summary>
        internal static string minVer {
            get {
                return ResourceManager.GetString("minVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Version Compatibility:.
        /// </summary>
        internal static string minVerCom {
            get {
                return ResourceManager.GetString("minVerCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC Version: .
        /// </summary>
        internal static string rcVer {
            get {
                return ResourceManager.GetString("rcVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC Version Compatibility: .
        /// </summary>
        internal static string rcVerCom {
            get {
                return ResourceManager.GetString("rcVerCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap roundedRectangle {
            get {
                object obj = ResourceManager.GetObject("roundedRectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap roundedRectangle1 {
            get {
                object obj = ResourceManager.GetObject("roundedRectangle1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
